### ISSUE TITLE
Integrate new test cases for us to support different hashes for different networks

### ISSUE THREAD

**Issue by caseyturnerarrington** [onflow/ledger-app-flow#4]
As discussed via slack:

Summary:
We want to support multiple chain IDs (flow-emulator , flow-testnet and flow-mainnet) when using our ledger integration. To do this, we will include the chain ID in the transaction signing request. This way we avoid having to publish multiple versions of the binary with different code hashes.

This task:
Once @psiemens  provides you test cases that are representative of this, please adjust things on the ledger side of the world to support these 3 different hashes

(task for Juan)

**Comment by psiemens** [comment]
I added the additional test cases in this PR and also did some of preliminary work to support multiple chains: https://github.com/onflow/ledger-app-flow/pull/5

### Part 1: Support token transfers on all networks

This is now the complete list of transaction templates we need to support in the Ledger app:
- `Create Account` (works on all chains)
- `AddAccountKey` (works on all chains)
- `TransferTokens` (Emulator)
- `TransferTokens` (Testnet)
- `TransferTokens` (Mainnet)

The three `Transfer Tokens` are identical _except_ for the import address they use. This means that the Ledger app should parse and display their arguments in the same way (which hopefully reduces the amount of code to add/change). I was able to achieve this by simply adding the additional hashes to this conditional:

https://github.com/onflow/ledger-app-flow/blob/5e9b9683cce4ed03a6f610db8ed5841664110c68/app/src/parser_impl.c#L254-L260

However, the problem here is that the user does not know which network matched! That's where the next part comes in...

### Part 2: Derive chain ID from transactions

Although we don't _need_ to display the chain ID for all transactions, our team made the following product decision today:

> We want to display the chain ID (Emulator, Testnet, Mainnet) for every transaction, not just token transfers. This is an extra piece of protection for the Ledger user.

The easiest way for us to do this is by deriving the chain ID from the transaction payer address. @tarakby has offered to help write the code for this part.

Here's my proposed spec as pseudocode:

```c
typedef enum {
    chain_id_unknown,
    chain_id_emulator,
    chain_id_testnet,
    chain_id_mainnet,
} chain_id_e;

parser_error_t chainIDFromPayer(const flow_payer_t *v, chain_id_e *chainID) { 
 // implementation provided by Dapper...
} 

parser_error_t parser_printChainID(const chain_id_e *v,
                                    char *outVal, uint16_t outValLen,
                                    uint8_t pageIdx, uint8_t *pageCount) {

  // Add a page to the app that includes the following:
  //
  // Chain: Mainnet
}

cc @jleni

**Comment by psiemens** [comment]
Closed by https://github.com/onflow/ledger-app-flow/pull/5
